# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Datastore_pb2 as Datastore__pb2


class DatastoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getConnection = channel.unary_stream(
        '/Datastore/getConnection',
        request_serializer=Datastore__pb2.ConnectionRequest.SerializeToString,
        response_deserializer=Datastore__pb2.ConnectionResponse.FromString,
        )
    self.operation = channel.unary_unary(
        '/Datastore/operation',
        request_serializer=Datastore__pb2.Request.SerializeToString,
        response_deserializer=Datastore__pb2.Response.FromString,
        )


class DatastoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getConnection(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def operation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DatastoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getConnection': grpc.unary_stream_rpc_method_handler(
          servicer.getConnection,
          request_deserializer=Datastore__pb2.ConnectionRequest.FromString,
          response_serializer=Datastore__pb2.ConnectionResponse.SerializeToString,
      ),
      'operation': grpc.unary_unary_rpc_method_handler(
          servicer.operation,
          request_deserializer=Datastore__pb2.Request.FromString,
          response_serializer=Datastore__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Datastore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
